name: Generate dictionary using MAJESTIC file
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate the dict
      run: |
        wget http://downloads.majestic.com/majestic_million.csv
        cat majestic_million.csv | awk -F  "," 'NR>1 {print $1 "," $3}' > input.csv
        python dict_builder.py -n 1000000 -t 100 -f input.csv -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt disallowed_entries_dict_majestic.txt
        rm input.csv
        git config --global user.email "github-action-job@github.com"
        git config --global user.name "GitHubActionJob"
        git commit -m "Update version with freshly generated content." disallowed_entries_dict_majestic.txt
        git push

