name: Generate dictionaries for CISCO and MAJESTIC sources
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download and prepare the combined source
      run: |        
        wget -q http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip
        wget -q http://downloads.majestic.com/majestic_million.csv
        unzip top-1m.csv.zip
        cat majestic_million.csv | awk -F  "," 'NR>1 {print $1 "," $3}' > input.csv
        cat top-1m.csv | awk -F  "," 'NR>1 {print "0," $2}' > D1.csv
        cat input.csv | awk -F  "," 'NR>1 {print "0," $2}' > D2.csv
        cat D1.csv D2.csv | sort -u > data.csv
        split -l 600000 data.csv part
        rm top-1m.csv.zip top-1m.csv majestic_million.csv D1.csv D2.csv data.csv
    - name: Generate the dict using PART 1/4 to stay under 6H
      run: |
        python dict_builder.py -n 600000 -t 150 -f partaa -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt part1.txt
    - name: Generate the dict using PART 2/4 to stay under 6H
      run: |
        python dict_builder.py -n 600000 -t 150 -f partab -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt part2.txt
    - name: Generate the dict using PART 3/4 to stay under 6H
      run: |
        python dict_builder.py -n 600000 -t 150 -f partac -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt part3.txt       
    - name: Generate the dict using PART 4/4 to stay under 6H
      run: |
        python dict_builder.py -n 600000 -t 150 -f partad -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt part4.txt
    - name: Commit and push the generated content
      run: |
        cat part1.txt part2.txt part3.txt part4.txt > disallowed_entries_dict.txt
        ls -l
        git config --global user.email "github-action-job@github.com"
        git config --global user.name "GitHubActionJob"
        git commit -m "Update version with freshly generated content." disallowed_entries_dict.txt
        git push
