name: Generate dictionaries for CISCO and MAJESTIC sources
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate the dict using CISCO source
      run: |
        wget -q http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip
        unzip top-1m.csv.zip
        python dict_builder.py -n 1000000 -t 100 -f top-1m.csv -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt disallowed_entries_dict_cisco.txt
        rm top-1m.csv.zip
        rm top-1m.csv
    - name: Generate the dict using MAJESTIC source
      run: |
        wget http://downloads.majestic.com/majestic_million.csv
        cat majestic_million.csv | awk -F  "," 'NR>1 {print $1 "," $3}' > input.csv
        python dict_builder.py -n 1000000 -t 100 -f input.csv -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        mv disallowed_entries_dict.txt disallowed_entries_dict_majestic.txt
        rm input.csv
        rm majestic_million.csv
        git config --global user.email "github-action-job@github.com"
        git config --global user.name "GitHubActionJob"
        git commit -m "Update version with freshly generated content." disallowed_entries_dict_majestic.txt disallowed_entries_dict_cisco.txt
        git push
