name: Generate dictionary
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate the dict
      run: |
        wget -q http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip
        unzip top-1m.csv.zip
        python dict_builder.py -n 550000 -t 60 -f top-1m.csv -m 5 -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9"
        wc -l disallowed_entries_dict.txt
        rm top-1m.csv.zip
        rm top-1m.csv
        git config --global user.email "github-action-job@github.com"
        git config --global user.name "GitHubActionJob"
        git commit -m "Update version with freshly generated content." disallowed_entries_dict.txt
        git push

